title: uebersystems
description: "Essays on technology, responsibility, and decision-making"
url: "https://uebersystems.com"
baseurl: ""
author: "Sven-Torben"

# Keep it simple and predictable
markdown: kramdown

# Pretty URLs
permalink: /essays/:title/

# Plugins for SEO and Sitemap
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Optional: keep future posts visible locally if you draft ahead
future: true

theme:
remote_theme:
